spring:
  datasource:
    url: jdbc:mysql://localhost:3306/surajmaity1?useSSL=false
    username: root
    password: 123456


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


   #The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



  # JPA SETTINGS
  jpa.hibernate.ddl_auto: create


# actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/employee-management-dashboard"
  endpoint:
    health:
      show-details: always


testingService:
  port: 8082
  address: 127.0.0.1


# Enable Debug Logging for specific package
logging:
  level:
    com.surajmaity1.springbootrestapi.controller: DEBUG


# Enable Debug Logging for entire project
# Note: This is not a good idea
#logging:
#  level:
#    root: DEBUG